meta_product_name: "Q-Coffee"
meta_title: "Q-Coffee - Ache o cafe perfeito para voce"
meta_description: "Pesquise cafes a partir de fotos e descubra novos gostos"
meta_image: "logo-q.png" # should exist in `app/assets/images/`
# twitter_account: "@yoohoodco"   # required for Twitter Cards
# fb_id: "453057622213119"
